version: '3.8'

services:
  app:
    image: esteban889/proyectofinal-3:latest
    container_name: threaderz_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 12345
      DB_NAME: threaderz_store
    restart: always
    networks:
      - threaderz-network

  db:
    image: esteban889/threaderz-mysql:latest  # ‚Üê Imagen personalizada con datos
    container_name: threaderz_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: threaderz_store
    ports:
      - "3306:3306"
    networks:
      - threaderz-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  threaderz-network:
    driver: bridge